
CREATE TABLE TIPO_SKILL (
                TIPO_SKILL VARCHAR NOT NULL,
                DESCRICAO_DO_TIPO_SKILL VARCHAR NOT NULL,
                CONSTRAINT tipo_skill_pk PRIMARY KEY (TIPO_SKILL)
);


CREATE TABLE CARGOS (
                CARGO_CODIGO VARCHAR(2) NOT NULL,
                NOME VARCHAR NOT NULL,
                CONSTRAINT cargos_codigo PRIMARY KEY (CARGO_CODIGO)
);
COMMENT ON TABLE CARGOS IS 'Essa tabela armazena informações sobre os cargos que os colaboradores podem ocupar.';


CREATE TABLE SOFTSKILLS (
                SS_CODIGO VARCHAR(2) NOT NULL,
                NOME VARCHAR NOT NULL,
                TIPO_SKILL VARCHAR NOT NULL,
                CONSTRAINT ss_codigo PRIMARY KEY (SS_CODIGO)
);
COMMENT ON TABLE SOFTSKILLS IS 'Essa tabela armazena informações sobre as softskills que os colaboradores podem possuir.';


CREATE TABLE HARDSKILLS (
                HS_CODIGO VARCHAR(2) NOT NULL,
                NOME VARCHAR NOT NULL,
                TIPO_SKILL VARCHAR NOT NULL,
                CONSTRAINT hs_codigo PRIMARY KEY (HS_CODIGO)
);
COMMENT ON TABLE HARDSKILLS IS 'Essa tabela guarda informações sobre as hardskills que os colaboradores podem possuir.';


CREATE TABLE DEPARTAMENTO (
                DEPT_CODIGO VARCHAR(2) NOT NULL,
                NOME VARCHAR NOT NULL,
                CONSTRAINT dept_codigo PRIMARY KEY (DEPT_CODIGO)
);
COMMENT ON TABLE DEPARTAMENTO IS 'Essa tabela guarda informações referentes aos departamentos.';


CREATE TABLE COLABORADORES (
                CPF NUMERIC(11) NOT NULL,
                NOME VARCHAR NOT NULL,
                DATA_ADMISSAO DATE NOT NULL,
                SEXO VARCHAR(1),
                DEPT_CODIGO VARCHAR(2) NOT NULL,
                CARGO_CODIGO VARCHAR(2) NOT NULL,
                CONSTRAINT cpf PRIMARY KEY (CPF)
);
COMMENT ON TABLE COLABORADORES IS 'Essa tabela faz referência aos colaboradores, principais ativos da empresa.';


CREATE TABLE EMAILS (
                EMAIL VARCHAR NOT NULL,
                CPF NUMERIC(11) NOT NULL,
                CONSTRAINT email PRIMARY KEY (EMAIL)
);
COMMENT ON TABLE EMAILS IS 'Essa tabela guarda informações sobre os e-mails de telefones dos colaboradores.';


CREATE TABLE HS_QUE_POSSUI (
                CPF NUMERIC(11) NOT NULL,
                HS_CODIGO VARCHAR(2) NOT NULL,
                PROEFICIENCIA NUMERIC(2) NOT NULL,
                CONSTRAINT cpf PRIMARY KEY (CPF, HS_CODIGO)
);
COMMENT ON TABLE HS_QUE_POSSUI IS 'Essa tabela relaciona quais hardskills cada colaborador possui.';


CREATE TABLE CERTIFICACOES (
                CPF NUMERIC(11) NOT NULL,
                HS_CODIGO VARCHAR(2) NOT NULL,
                CERTIFICADO_CODIGO VARCHAR(2) NOT NULL,
                NOME VARCHAR NOT NULL,
                PROVEDOR VARCHAR NOT NULL,
                DATA_EMISSAO DATE NOT NULL,
                DATA_EXPIRACAO DATE,
                CONSTRAINT cpf PRIMARY KEY (CPF, HS_CODIGO, CERTIFICADO_CODIGO, NOME)
);
COMMENT ON TABLE CERTIFICACOES IS 'Essa tabela guarda informações sobre as diversas certificações que um colaborador pode possuir sobre uma hardskill específica';


CREATE TABLE SS_QUE_POSSUI (
                CPF NUMERIC(11) NOT NULL,
                SS_CODIGO VARCHAR(2) NOT NULL,
                PROEFICIENCIA NUMERIC(2) NOT NULL,
                CONSTRAINT cpf PRIMARY KEY (CPF, SS_CODIGO)
);
COMMENT ON TABLE SS_QUE_POSSUI IS 'Essa tabela relaciona quais softskills cada colaborador possui.';


CREATE TABLE TELEFONES (
                DDD NUMERIC(2) NOT NULL,
                NUMERO_TELEFONE NUMERIC(9) NOT NULL,
                CPF NUMERIC(11) NOT NULL,
                CONSTRAINT numero_telefone PRIMARY KEY (DDD, NUMERO_TELEFONE)
);
COMMENT ON TABLE TELEFONES IS 'Essa tabela guarda informações sobre os números de telefones dos colaboradores.';


CREATE TABLE ENDERECOS (
                CEP NUMERIC NOT NULL,
                NUMERO NUMERIC(10) NOT NULL,
                CPF NUMERIC(11) NOT NULL,
                CONSTRAINT cep PRIMARY KEY (CEP, NUMERO)
);
COMMENT ON TABLE ENDERECOS IS 'Essa tabela guarda informações sobre os endereços dos colaboradores';


ALTER TABLE SOFTSKILLS ADD CONSTRAINT tipo_skill_softskills_fk
FOREIGN KEY (TIPO_SKILL)
REFERENCES TIPO_SKILL (TIPO_SKILL)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE HARDSKILLS ADD CONSTRAINT tipo_skill_hardskills_fk
FOREIGN KEY (TIPO_SKILL)
REFERENCES TIPO_SKILL (TIPO_SKILL)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE COLABORADORES ADD CONSTRAINT cargos_colaboradores_fk
FOREIGN KEY (CARGO_CODIGO)
REFERENCES CARGOS (CARGO_CODIGO)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE SS_QUE_POSSUI ADD CONSTRAINT softskills_ss_que_possui_fk
FOREIGN KEY (SS_CODIGO)
REFERENCES SOFTSKILLS (SS_CODIGO)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE HS_QUE_POSSUI ADD CONSTRAINT hardskills_hs_que_possui_fk
FOREIGN KEY (HS_CODIGO)
REFERENCES HARDSKILLS (HS_CODIGO)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE COLABORADORES ADD CONSTRAINT departamento_colaboradores_fk
FOREIGN KEY (DEPT_CODIGO)
REFERENCES DEPARTAMENTO (DEPT_CODIGO)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE ENDERECOS ADD CONSTRAINT colaboradores_enderecos_fk
FOREIGN KEY (CPF)
REFERENCES COLABORADORES (CPF)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE TELEFONES ADD CONSTRAINT colaboradores_telefones_fk
FOREIGN KEY (CPF)
REFERENCES COLABORADORES (CPF)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE SS_QUE_POSSUI ADD CONSTRAINT colaboradores_ss_que_possui_fk
FOREIGN KEY (CPF)
REFERENCES COLABORADORES (CPF)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE HS_QUE_POSSUI ADD CONSTRAINT colaboradores_hs_que_possui_fk
FOREIGN KEY (CPF)
REFERENCES COLABORADORES (CPF)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE EMAILS ADD CONSTRAINT colaboradores_emails_fk
FOREIGN KEY (CPF)
REFERENCES COLABORADORES (CPF)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE CERTIFICACOES ADD CONSTRAINT hs_que_possui_certificacoes_fk
FOREIGN KEY (CPF, HS_CODIGO)
REFERENCES HS_QUE_POSSUI (CPF, HS_CODIGO)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;
